---

crayfish_version_tag: dev-format_jsonld_strip

crayfish_db: "{{ claw_db }}"

crayfish_milliner_drupal_base_url: http://localhost:8000
crayfish_milliner_gemini_base_url: http://localhost:8000/gemini
