- name: Start Karaf
  shell: >
    JAVA_HOME={{ karaf_java_home }}
    KARAF_HOME={{ karaf_install_symlink }}
    {{ karaf_install_symlink }}/bin/start && sleep 5
  args:
    chdir: "{{ karaf_install_symlink }}/bin"
    creates: "{{ karaf_install_symlink }}/bin/karaf-wrapper"
  become_user: "{{ karaf_user }}"
  register: karaf_service_install

- name: Wait for Karaf to start
  wait_for:
    port: 8101
  when: karaf_service_install.changed is defined and karaf_service_install.changed

- name: Install wrapper feature
  command: ./client feature:install wrapper
  args:
    chdir: "{{ karaf_install_symlink }}/bin"
  become_user: "{{ karaf_user }}"
  when: karaf_service_install.changed is defined and karaf_service_install.changed

- name: Install wrapper
  command: ./client wrapper:install
  args:
    chdir: "{{ karaf_install_symlink }}/bin"
  become_user: "{{ karaf_user }}"
  when: karaf_service_install.changed is defined and karaf_service_install.changed

- name: Stop Karaf
  shell: >
    JAVA_HOME={{ karaf_java_home }}
    KARAF_HOME={{ karaf_install_symlink }}
    {{ karaf_install_symlink }}/bin/stop && sleep 1
  args:
    chdir: "{{ karaf_install_symlink }}/bin"
  become_user: "{{ karaf_user }}"
  when: karaf_service_install.changed is defined and karaf_service_install.changed

- name: Copy templated Karaf definition
  template:
    src: "{{ karaf_systemd_template }}"
    dest: "{{ karaf_install_symlink }}/bin/karaf.service"
    owner: "{{ karaf_user }}"
    group: "{{ karaf_user }}"

- name: Install Karaf service in systemd
  command: systemctl enable {{ karaf_install_symlink }}/bin/karaf.service
  args:
    creates: /etc/systemd/system/karaf

- name: Start Karaf service
  service:
    name: karaf
    state: started
