---

- name: Create maven repository directory
  file:
    state: directory
    path: "{{ alpaca_local_mvn_path }}"

- name: Create maven repository directory
  file:
    state: directory
    path: "~/.m2"

- name: Drop in templated Maven settings
  template:
    src: maven.xml.j2
    dest: "~/.m2/settings.xml"

- name: Clone CLAW Alpaca
  git:
    repo: https://github.com/dannylamb/Alpaca.git
    dest: "{{ alpaca_clone_directory }}"
    version: "{{ alpaca_version }}"
  register: alpaca_git

- name: Install Alpaca via Gradle
  command: ./gradlew install
  args:
    chdir: "{{ alpaca_clone_directory }}"
  when: alpaca_git.changed

- name: Make sure karaf has permissions to directory
  file:
    state: directory
    path: "{{ alpaca_local_mvn_path }}"
    recurse: yes
    owner: "{{ alpaca_karaf_user }}"
    group: "{{ alpaca_karaf_user }}"

- name: Add local maven repository to karaf
  lineinfile:
    state: present
    path: "{{alpaca_karaf_dir}}/etc/org.ops4j.pax.url.mvn.cfg"
    insertafter: ^#org\.ops4j\.pax\.url\.mvn\.localRepository=$
    line: org.ops4j.pax.url.mvn.localRepository={{ alpaca_local_mvn_path }}
    regexp: ^org\.ops4j\.pax\.url\.mvn\.localRepository=
