---

alpaca_from_source: no
alpaca_version: main
alpaca_clone_directory: /opt/alpaca
alpaca_jar_path: "{{ alpaca_clone_directory }}/islandora-alpaca-app/build/libs/islandora-alpaca-app-2.0.0-all.jar"

alpaca_user: tomcat
alpaca_group: tomcat

alpaca_log_level: INFO

triplestore_namespace: islandora
alpaca_triplestore_base_url: http://localhost:8080/bigdata
alpaca_milliner_base_url: http://localhost:8000/milliner
alpaca_gemini_base_url: http://localhost:8000/gemini
alpaca_houdini_base_url: http://localhost:8000/houdini
alpaca_homarus_base_url: http://localhost:8000/homarus
alpaca_fits_base_url: http://localhost:8000/crayfits

alpaca_error_maxRedeliveries: 5

alpaca_jms_baseUrl: tcp://localhost:61616
alpaca_jms_username:
alpaca_jms_password:
alpaca_jms_connections: 10

alpaca_request_configurer_enabled: false
alpaca_request_configurer_request_timeout: -1
alpaca_request_configurer_connection_timeout: -1
alpaca_request_configurer_socket_timeout: -1

alpaca_fcrepo_enabled: true
alpaca_fcrepo_milliner_baseUrl: "{{ alpaca_milliner_base_url }}"
alpaca_fcrepo_node: queue:islandora-indexing-fcrepo-content
alpaca_fcrepo_node_delete: queue:islandora-indexing-fcrepo-delete
alpaca_fcrepo_media: queue:islandora-indexing-fcrepo-media
alpaca_fcrepo_external: queue:islandora-indexing-fcrepo-external
alpaca_fcrepo_concurrent_consumers: -1
alpaca_fcrepo_max_consumers: -1

alpaca_triplestore_enabled: true
alpaca_triplestore_baseUrl: "{{ alpaca_triplestore_base_url }}/namespace/{{ triplestore_namespace }}/sparql"
alpaca_triplestore_input_stream: queue:islandora-indexing-triplestore-index
alpaca_triplestore_delete_stream: queue:islandora-indexing-triplestore-delete
alpaca_triplestore_concurrent_consumers: -1
alpaca_triplestore_max_consumers: -1

alpaca_derivative_connectors:
  - name: ocr
    enabled: true
    in_stream: queue:islandora-connector-ocr
    service_url: http://localhost:8000/hypercube
    concurrent-consumers: -1
    max-consumers: -1
  - name: houdini
    enabled: true
    in_stream: queue:islandora-connector-houdini
    service_url: "{{ alpaca_houdini_base_url }}/convert"
    concurrent-consumers: -1
    max-consumers: -1
  - name: homarus
    enabled: true
    in_stream: queue:islandora-connector-homarus
    service_url: "{{ alpaca_homarus_base_url }}/convert"
    concurrent-consumers: -1
    max-consumers: -1
  - name: fits
    enabled: true
    in_stream: queue:islandora-connector-fits
    service_url: "{{ alpaca_fits_base_url }}"
    concurrent-consumers: -1
    max-consumers: -1
