---

- name: "Install FITS web service {{ansible_os_family}}"
  get_url:
    url: http://projects.iq.harvard.edu/files/fits/files/fits-{{ fits_ws_version }}.war
    dest: "{{ tomcat9_home }}/webapps/fits.war"
    owner: "{{ fits_user }}"
    group: "{{ fits_group }}"
    checksum: "{{fits_ws_md5sum}}"
  retries: 5
  register: result
  until: result is succeeded
