---
services: docker

env:
  - playbook=pgsql.yml distro=ubuntu1804
  - playbook=mysql.yml distro=ubuntu1804
# - playbook=pgsql.yml distro=centos7
# - playbook=mysql.yml distro=centos7

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh
