---
services: docker

env:
# - distro: centos7
  - distro=ubuntu1804 playbook=web_xml.yml
  - distro=ubuntu1804 playbook=java_opts.yml

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh
