karaf_version: 4.0.8
karaf_staging_folder: /usr/local/src
karaf_install_folder: /opt
karaf_install_symlink: /opt/karaf
karaf_user: karaf
karaf_create_user: yes
karaf_service_name: karaf

karaf_log_root_level: INFO
karaf_log_camel_level: DEBUG
karaf_log_islandora_level: DEBUG
karaf_log_path: ${karaf.data}/log/

karaf_logging_template: org.ops4j.pax.logging.cfg
karaf_maven_template: org.ops4j.pax.url.mvn.cfg

karaf_systemd_template: karaf.service

# The following variables have a default value depending on operating system.
# karaf_java_home: /usr/lib/jvm/java-8-openjdk-amd64
# karaf_java_packages:
#   - java-1.8.0-openjdk
#   - java-1.8.0-openjdk-devel
