---

- name: Create Gemini DB (mysql)
  mysql_db:
    name: "{{ crayfish_db_name }}"
    state: present
  register: gemini_db_exists

- name: Create Gemini DB User (mysql)
  mysql_user:
    name: "{{ crayfish_db_user }}"
    password: "{{ crayfish_db_password }}"
    state: present
    priv: "{{crayfish_db_name}}.*:ALL"

- name: Grab Gemini db schema (mysql)
  template:
    src: "gemini.sql"
    dest: "/tmp/gemini.sql"
  when: gemini_db_exists.changed

- name: Install Gemini db schema (mysql)
  mysql_db:
    state: import
    name: all
    target: "/tmp/gemini.sql"
  when: gemini_db_exists.changed
