---

httpd_conf_directory_enabled: "{{httpd_conf_directory}}/conf-enabled"

__crayfish_user: www-data
__httpd_conf_directory: /etc/apache2
__crayfish_packages:
  - imagemagick
  - tesseract-ocr
  - tesseract-ocr-fra
  - tesseract-ocr-deu
  - tesseract-ocr-ita
  - tesseract-ocr-spa
  - tesseract-ocr-srp
  - ffmpeg
  - poppler-utils
__crayfish_db: mysql
