---

httpd_conf_directory_enabled: "{{httpd_conf_directory}}/conf.d"

__crayfish_user: apache
__httpd_conf_directory: /etc/httpd
__crayfish_packages:
  - ghostscript
  - ImageMagick
  - tesseract
  - tesseract-langpack-fra
  - tesseract-langpack-deu
  - tesseract-langpack-ita
  - tesseract-langpack-spa
  - tesseract-langpack-srp
  - ffmpeg
  - poppler-utils
__crayfish_db: mysql
