---

fcrepo_syn_version: 0.1.0
fcrepo_syn_folder: /opt/syn
fcrepo_syn_user: tomcat8
fcrepo_syn_tomcat_home: /var/lib/tomcat8
fcrepo_syn_sites: []
# - url:
#   algorithm:
#   encoding:
#   anonymous:
#   default:
#   path:
#   key:
fcrepo_syn_tokens: []
# - user:
# - roles:
# - token:
