---

- name: Get SSL keys
  include_role: 
    name: Islandora-Devops.keymaster
  vars:
    ssl_key_public_output_path: "{{ fcrepo_syn_default_public_key_path }}"

- name: Copy templated syn-settings.xml
  template:
    src: syn-settings.xml
    dest: "{{ fcrepo_syn_tomcat_config_dir }}/syn-settings.xml"
    owner: "{{ fcrepo_syn_user }}"
    group: "{{ fcrepo_syn_user }}"

- name: Add valve
  lineinfile:
    path: "{{ fcrepo_syn_tomcat_config_dir }}/context.xml"
    line: "<Valve className=\"ca.islandora.syn.valve.SynValve\" pathname=\"{{ fcrepo_syn_tomcat_config_dir }}/syn-settings.xml\" />"
    insertbefore: "</Context>"
