---

- name: Create syn home folder
  file:
    state: directory
    path: "{{ fcrepo_syn_folder }}"
    owner: "{{ fcrepo_syn_user }}"
    group: "{{ fcrepo_syn_user }}"

- name: Download syn jar file
  get_url:
    url: https://github.com/Islandora-CLAW/Syn/releases/download/v{{ fcrepo_syn_version }}/islandora-syn-{{ fcrepo_syn_version }}-all.jar
    dest: "{{ fcrepo_syn_folder }}"
    owner: "{{ fcrepo_syn_user }}"
    group: "{{ fcrepo_syn_user }}"

- name: Move syn jar to webapp
  copy:
    src: "{{ fcrepo_syn_folder }}/islandora-syn-{{ fcrepo_syn_version }}-all.jar"
    dest: "{{ fcrepo_syn_tomcat_home }}/lib/"
    remote_src: yes
    owner: "{{ fcrepo_syn_user }}"
    group: "{{ fcrepo_syn_user }}"
